/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_github_dongjinleekr_beanpiece_Processor */

#ifndef _Included_com_github_dongjinleekr_beanpiece_Processor
#define _Included_com_github_dongjinleekr_beanpiece_Processor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_github_dongjinleekr_beanpiece_Processor
 * Method:    getString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_github_dongjinleekr_beanpiece_Processor_getString
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
