/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_github_dongjinleekr_beanpiece_Processor */

#ifndef _Included_com_github_dongjinleekr_beanpiece_Processor
#define _Included_com_github_dongjinleekr_beanpiece_Processor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_github_dongjinleekr_beanpiece_Processor
 * Method:    load
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_github_dongjinleekr_beanpiece_Processor_load
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_github_dongjinleekr_beanpiece_Processor
 * Method:    encode
 * Signature: (Ljava/lang/String;)Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_com_github_dongjinleekr_beanpiece_Processor_encode
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
