/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_dongjinlee_beanpiece_Processor */

#ifndef _Included_com_dongjinlee_beanpiece_Processor
#define _Included_com_dongjinlee_beanpiece_Processor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_dongjinlee_beanpiece_Processor
 * Method:    load
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_dongjinlee_beanpiece_Processor_load
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_dongjinlee_beanpiece_Processor
 * Method:    encodeToPieces
 * Signature: (Ljava/lang/String;)Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_com_dongjinlee_beanpiece_Processor_encodeToPieces
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_dongjinlee_beanpiece_Processor
 * Method:    encodeToIds
 * Signature: (Ljava/lang/String;)Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_com_dongjinlee_beanpiece_Processor_encodeToIds
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_dongjinlee_beanpiece_Processor
 * Method:    decodePieces
 * Signature: (Ljava/util/List;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_dongjinlee_beanpiece_Processor_decodePieces
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_dongjinlee_beanpiece_Processor
 * Method:    decodeIds
 * Signature: (Ljava/util/List;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_dongjinlee_beanpiece_Processor_decodeIds
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
